project_id = "vhkjwtwtroiqmdjlvwqd"

[functions.create-doctor-account]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.manage-doctor-account]
verify_jwt = false

[functions.manage-patient-account]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.generate-honorarnote]
verify_jwt = false

[functions.generate-consultation-report]
verify_jwt = false
